config/routes.rb
Rails.application.routes.draw do
  root to: "issue_reports#index"

  resources :issues, :path => 'categorias'
  get "/problemas_resolvidos", to: 'issue_reports#resolvidos', as: :issue_reports_resolvidos
  resources :issue_reports, :except => [:new, :create], :path => 'problemas' do
    resources :resolution_report, :only => [:new, :create, :destroy]
  end

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  use_doorkeeper
  mount API::Base => '/'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :issue_reports, :dependent => :delete_all
  validates :name, uniqueness: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order(:id)
    @issue = Issue.new
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    render :layout => false
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
    render :layout => false
  end

  # POST /issues
  # POST /issues.json
  def create
    authenticate_admin
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to action: "index", notice: 'Issue was successfully created.' }
        format.json { render action: "index", status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to action: "index", notice: 'Issue was successfully updated.' }
        format.json { render action: "index", status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.slim
= form_for(@issue) do |f|
  - if @issue.errors.any?
    #error_explanation"
      h2
        = pluralize(@issue.errors.count, "error")
        ' prohibited this issue from being saved:

      ul
      - @issue.errors.full_messages.each do |message|
        li
          = message

  .mdl-textfield.mdl-js-textfield style="width: 100%;"
    = f.label :name, 'Nome', :class => "mdl-textfield__label"  
    = f.text_field :name, :class => "mdl-textfield__input"

  div
    = f.submit 'Salvar', :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"

app/views/issues/edit.html.slim
div.white-popup-block.small-dialog  
  h4 Editar categoria  
  = render 'form'

app/views/issues/index.html.slim
.title-subheader style="position: relative;"
  h2.display-1
    span class="ca ca-category"
    '  Categorias de problemas
  
  - if authenticate_admin?
    button href="#new_form" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored md-fab-float new_popup"
      i class="ca ca-plus"

- if authenticate_admin?
  div#new_form.white-popup-block.mfp-hide.small-dialog  
    h4 Nova categoria  
    = render 'form'

.mdl-grid style="margin-top: 30px;"
  table.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp.mdl-cell.mdl-cell--12-col
    thead
      tr
        th.mdl-data-table__cell--non-numeric style="width: 80%;" Tipo
        th.mdl-data-table__cell--non-numeric.text-center Editar
        th.mdl-data-table__cell--non-numeric.text-center Deletar
    tbody
      - @issues.each do |issue|
        tr
          td.mdl-data-table__cell--non-numeric = issue.name
          td.mdl-data-table__cell--non-numeric.text-center 
             = link_to edit_issue_path(issue), :class => 'mdl-button btn-table-fix edit_popup'
              span class="ca ca-edit"

          td.mdl-data-table__cell--non-numeric.text-center 
            = link_to issue, method: :delete, data: { confirm: 'Tem certeza que deseja remover esse item?' }, :class => "mdl-button btn-table-fix" do
              span class="ca ca-delete"

javascript:
  $(document).ready(function() {
    $('.new_popup').magnificPopup({
      type: 'inline',
      fixedContentPos: false,
      fixedBgPos: true,
      overflowY: 'auto',
      closeBtnInside: true,
      preloader: false,
      midClick: true,
      removalDelay: 300,
      mainClass: 'my-mfp-zoom-in'
    });

    $('.edit_popup').magnificPopup({
      type: 'ajax',
      fixedContentPos: false,
      fixedBgPos: true,
      overflowY: 'auto',
      closeBtnInside: true,
      preloader: false,
      midClick: true,
      removalDelay: 300,
      mainClass: 'my-mfp-zoom-in'
    });

  });

app/views/issues/new.html.slim
div#new_form.white-popup-block.mfp-hide.small-dialog
  h4 Nova categoria  
  = form_for(@issue) do |f|
    - if @issue.errors.any?
      #error_explanation"
        h2
          = pluralize(@issue.errors.count, "error")
          ' prohibited this issue from being saved:

        ul
        - @issue.errors.full_messages.each do |message|
          li
            = message

    .mdl-textfield.mdl-js-textfield style="width: 100%;"
      = f.label :name, 'Nome', :class => "mdl-textfield__label"  
      = f.text_field :name, :class => "mdl-textfield__input"

    div
      = f.submit 'Salvar', :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"

app/views/issues/show.html.slim
p
  strong
    ' Name:
    
  = @issue.name