config/routes.rb
Rails.application.routes.draw do
  root to: "issue_reports#index"

  resources :issues, :path => 'categorias'
  get "/problemas_resolvidos", to: 'issue_reports#resolvidos', as: :issue_reports_resolvidos
  resources :issue_reports, :except => [:new, :create], :path => 'problemas' do
    resources :resolution_report, :only => [:new, :create, :destroy]
  end

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  use_doorkeeper
  mount API::Base => '/'
end

app/models/resolution_report.rb
class ResolutionReport < ActiveRecord::Base
  belongs_to :issue_report
  belongs_to :user

  validates :user,          presence: true
  validates :issue_report,  presence: true
  validates :description,   presence: true
end

app/controllers/resolution_report_controller.rb
class ResolutionReportController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue_report, only: [:create, :destroy]
  before_action :set_resolution_report, only: :destroy

  def new
    @resolution_report = ResolutionReport.new
  end

  def create
    authenticate_admin

    @resolution_report = ResolutionReport.new(issue_params)
    @resolution_report.issue_report = @issue_report
    @resolution_report.user = current_user

    respond_to do |format|
      if @resolution_report.save
        format.html { redirect_to @issue_report, notice: 'Resposta registrada' }
        format.json { render :show, status: :created, location: @issue_report }
      else
        format.html { redirect_to @issue_report }
        format.json { render json: @resolution_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user == @issue_report.user || current_user.admin != nil
      @resolution_report.destroy
      respond_to do |format|
        format.html { redirect_to issue_report_path(@issue_report), notice: 'Issue report was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      raise StandardError.new 'Access denied.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resolution_report
      @resolution_report = ResolutionReport.find(params[:id])
    end

    def set_issue_report
      @issue_report = IssueReport.find(params[:issue_report_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:resolution_report).permit(:description)
    end

end

app/helpers/resolution_report_helper.rb
module ResolutionReportHelper
end

app/views/resolution_report/_form.html.slim
= form_for [@issue_report, @resolution_report], url: issue_report_resolution_report_index_path(@issue_report) do |f|
  - if @resolution_report.errors.any?
    #error_explanation
      h2
        = pluralize(@resolution_report.errors.count, "error") 
        ' prohibited this issue from being saved:

      ul
      - @resolution_report.errors.full_messages.each do |message|
        li
          = message

     
  .mdl-textfield.mdl-js-textfield.mdl-cell.mdl-cell--12-col 
    = f.label :description, 'Resposta', :class => "mdl-textfield__label"  
    = f.text_field :description, autocomplete: "off", :class => "mdl-textfield__input"

  div
    = f.submit 'Salvar', :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"

app/views/resolution_report/new.html.slim
h1
  ' Resposta

= render 'form'