config/routes.rb
Rails.application.routes.draw do
  root to: "issue_reports#index"

  resources :issues, :path => 'categorias'
  get "/problemas_resolvidos", to: 'issue_reports#resolvidos', as: :issue_reports_resolvidos
  resources :issue_reports, :except => [:new, :create], :path => 'problemas' do
    resources :resolution_report, :only => [:new, :create, :destroy]
  end

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  use_doorkeeper
  mount API::Base => '/'
end

app/models/issue_report.rb
class IssueReport < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue

  has_one :resolution_report, :dependent => :delete

  has_attached_file :image, styles: { thumb: "100x100>" }, :dependent => :delete
  validates_attachment :image, :content_type => { :content_type => 'image/jpeg' }, :size => { :in => 0..5000.kilobytes }

  has_attached_file :video, :processors => [:transcoder], :dependent => :delete
  validates_attachment :video, :time => 10, :content_type => { :content_type => 'video/quicktime' }, :size => { :in => 0..1000.kilobytes }

end

app/controllers/issue_reports_controller.rb
class IssueReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue_report, only: [:show, :edit, :update, :destroy]

  # GET /issue_reports
  # GET /issue_reports.json
  def index
    @issue_not_resolvido = IssueReport
      .joins('LEFT JOIN resolution_reports ON resolution_reports.issue_report_id = issue_reports.id')
      .where('resolution_reports.issue_report_id IS null')
      .paginate(:page => params[:page], :per_page => 9)
      .order('issue_reports.created_at DESC')
  end

  def resolvidos
    @issue_resolvido = IssueReport.joins(:resolution_report)
      .paginate(:page => params[:page], :per_page => 9)
      .order('resolution_reports.created_at DESC')
  end

  # GET /issue_reports/1
  # GET /issue_reports/1.json
  def show
  end

  # GET /issue_reports/new
  def new
    @issue_report = IssueReport.new
  end

  # GET /issue_reports/1/edit
  def edit
  end

  # POST /issue_reports
  # POST /issue_reports.json
  def create
    @issue_report = IssueReport.new(issue_report_params)
    @issue_report.user = current_user

    respond_to do |format|
      if @issue_report.save
        format.html { redirect_to @issue_report, notice: 'Issue report was successfully created.' }
        format.json { render :show, status: :created, location: @issue_report }
      else
        format.html { render :new }
        format.json { render json: @issue_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issue_reports/1
  # PATCH/PUT /issue_reports/1.json
  def update
    respond_to do |format|
      if @issue_report.update(issue_report_params)
        format.html { redirect_to @issue_report, notice: 'Issue report was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue_report }
      else
        format.html { render :edit }
        format.json { render json: @issue_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issue_reports/1
  # DELETE /issue_reports/1.json
  def destroy
    @issue_report.destroy
    respond_to do |format|
      format.html { redirect_to issue_reports_url, notice: 'Issue report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue_report
      @issue_report = IssueReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_report_params
      params[:issue_report]
    end
end

app/helpers/issue_reports_helper.rb
module IssueReportsHelper
end

app/views/issue_reports/_issue_report.html.slim
= link_to issue_report, :class => "card_link"
  .info-card-wide.mdl-card.mdl-shadow--2dp.mdl-cell.mdl-cell--4-col
    - if (issue_report.image.url != '/images/original/missing.png')
      .mdl-card__title style="background-image: url(#{image_url(issue_report.image.url(:original))}); height: 175px;"
        h2.mdl-card__title-text style="color: #FFF;"
          - if issue_report.issue_id != nil
            = Issue.find(issue_report.issue_id).name
          - else
            ' Outro
    - else
      .mdl-card__title style="background-image: url(#{image_url('missing.jpg')}); height: 175px;"
        h2.mdl-card__title-text style="color: #FFF;"
          - if issue_report.issue_id != nil
            = Issue.find(issue_report.issue_id).name
          - else
            ' Outro

    .mdl-card__supporting-date style="color: rgba(0, 0, 0, 0.54); font-size: 13px; line-height: 18px; overflow: hidden; padding: 16px 16px 0px 16px; width: 90%;"
      span class="ca ca-calendar"
      = " " + issue_report.created_at.strftime("%d/%m/%Y às %H:%M")
    .mdl-card__supporting-text
      = truncate(issue_report.description, :length => 120)
    .mdl-card__actions.mdl-card--border
      a.mdl-button disabled="" style="color: #666;"
        span class="ca ca-place"
        = " " + issue_report.address
    .mdl-card__menu
      span.mdl-button.mdl-button--icon.mdl-js-button.mdl-js-ripple-effect.btn-padding  id="e-by-#{issue_report.id}" style="color: #FFF;"
        i.ca.ca-user
      div class="mdl-tooltip" for="e-by-#{issue_report.id}"
        ' Enviado por:
        = issue_report.user.login

app/views/issue_reports/_resolvido.html.slim
= link_to issue_report, :class => "card_link"
  .info-card-wide.mdl-card.mdl-shadow--2dp.mdl-cell.mdl-cell--4-col
    - if (issue_report.image.url != '/images/original/missing.png')
      .mdl-card__title style="background-image: url(#{image_url(issue_report.image.url(:original))}); height: 175px;"
        h2.mdl-card__title-text style="color: #FFF;"
          - if issue_report.issue_id != nil
            = Issue.find(issue_report.issue_id).name
          - else
            ' Outro
    - else
      .mdl-card__title style="background-image: url(#{image_url('missing.jpg')}); height: 175px;"
        h2.mdl-card__title-text style="color: #FFF;"
          - if issue_report.issue_id != nil
            = Issue.find(issue_report.issue_id).name
          - else
            ' Outro

    .mdl-card__supporting-date style="  color: rgba(0, 0, 0, 0.54); font-size: 13px; line-height: 18px; overflow: hidden; padding: 16px 16px 0px 16px; width: 90%;"
      span class="ca ca-calendar"
      = " " + issue_report.created_at.strftime("%d/%m/%Y às %H:%M")
    .mdl-card__supporting-text
      = truncate(issue_report.description, :length => 120)
    .mdl-card__actions.mdl-card--border
      a.mdl-button disabled="" style="color: #666;"
        span class="ca ca-place"
        = " " + issue_report.address
    .mdl-card__menu
      span.mdl-button.mdl-button--icon.mdl-js-button.mdl-js-ripple-effect.btn-padding  id="e-by-#{issue_report.id}" style="color: #FFF;"
        i.ca.ca-user
      div class="mdl-tooltip" for="e-by-#{issue_report.id}"
        ' Enviado por:
        = issue_report.user.login

app/views/issue_reports/index.html.slim
.title-subheader
  h2.display-1
    span.ca.ca-issue
    '  Problemas reportados

.mdl-tabs
  .mdl-tabs__tab-bar
    = link_to 'Problemas reportados', issue_reports_path, :class => "mdl-tabs__tab is-active", :style => "width: 50%"
    = link_to 'Problemas resolvidos', issue_reports_resolvidos_path, :class => "mdl-tabs__tab", :style => "width: 50%"

  .mdl-tabs__panel.is-active
    div class="mdl-grid"
      = render @issue_not_resolvido

    .mdl-grid
      .mdl-cell.mdl-cell--12-col
        = will_paginate @issue_not_resolvido, :previous_label => ' Anterior', :next_label => ' Pŕoximo'

app/views/issue_reports/resolvidos.html.slim
.title-subheader
  h2.display-1
    span.ca.ca-issue
    '  Problemas resolvidos

.mdl-tabs
  .mdl-tabs__tab-bar
    = link_to 'Problemas reportados', issue_reports_path, :class => "mdl-tabs__tab", :style => "width: 50%"
    = link_to 'Problemas resolvidos', issue_reports_resolvidos_path, :class => "mdl-tabs__tab is-active", :style => "width: 50%"

  .mdl-tabs__panel.is-active
    div class="mdl-grid"
      = render @issue_resolvido

    .mdl-grid
      .mdl-cell.mdl-cell--12-col
        = will_paginate @issue_resolvido, :previous_label => ' Anterior', :next_label => ' Pŕoximo'

app/views/issue_reports/show.html.slim
.title-subheader.show
  h2.display-1
    - if @issue_report.issue_id != nil
      = Issue.find(@issue_report.issue_id).name
    - else
      '  Outro
  h4.headline
    = @issue_report.address

  p
    b Enviado por:
    '
    = @issue_report.user.login



.mdl-grid
  div.mdl-shadow--2dp.mdl-cell.mdl-cell--12-col
    .mdl-grid
      .mdl-cell.mdl-cell--12-col
        - if !(@issue_report.video?)
          - if (@issue_report.image.url != '/images/original/missing.png')
            .details-card-image.mdl-card.media-style style="background-image: url(#{image_url(@issue_report.image.url(:thumb))});"
              .mdl-card__actions.mdl-card--border
                a href="#{image_url(@issue_report.image.url(:original))}"  title="#{(@issue_report.issue_id != nil)? Issue.find(@issue_report.issue_id).name : 'Outro' } em #{@issue_report.address}" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect test-popup-link"
                  span.ca.ca-expand
          - else
            .details-card-image.mdl-card.media-style style="background-image: url(#{image_url('missing.jpg')});"
              .mdl-card__actions.mdl-card--border
                a href="#{image_url('missing.jpg')}"  title="#{(@issue_report.issue_id != nil)? Issue.find(@issue_report.issue_id).name : 'Outro' } em #{@issue_report.address}" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect test-popup-link"
                 span.ca.ca-expand

        - if @issue_report.video?
          .media-style
            = video_tag @issue_report.video.url, :size => "320x240", :controls => true, :poster => @issue_report.image.url(:original)

        p = @issue_report.description

      div#map.mdl-cell.mdl-cell--12-col

      div.mdl-cell.mdl-cell--12-col
        - if !current_user.admin.nil? && @issue_report.resolution_report.nil?
          .mdl-grid
            .mdl-cell.mdl-cell--12-col
              h4 style="margin-bottom: 0px;" Responder

              - @resolution_report = @issue_report.build_resolution_report
              == render 'resolution_report/form'

        - elsif resolution_report = @issue_report.resolution_report
          h4 style="margin-bottom: 0px;" Resposta
          p
            strong Respondido em:
            '
            = resolution_report.created_at.strftime("%d/%m/%Y às %H:%M")
          p
            = resolution_report.description
          - if current_user.admin != nil
            td
              = link_to 'Deletar resposta', [@issue_report, resolution_report], method: :delete, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", data: { confirm: 'Tem certeza que deseja deletar essa resposta?' }




javascript:
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": #{@issue_report.latitude},
        "lng": #{@issue_report.longitude}
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(16);
  });

  $('.test-popup-link').magnificPopup({
    type: 'image',
    titleSrc: 'title'
  });