config/routes.rb
Rails.application.routes.draw do
  root to: "issue_reports#index"

  resources :issues, :path => 'categorias'
  get "/problemas_resolvidos", to: 'issue_reports#resolvidos', as: :issue_reports_resolvidos
  resources :issue_reports, :except => [:new, :create], :path => 'problemas' do
    resources :resolution_report, :only => [:new, :create, :destroy]
  end

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  use_doorkeeper
  mount API::Base => '/'
end

app/views/layouts/application.html.slim
doctype html
html lang="pt-br"
  head
    title Fiscal Cidadão
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region=" 
    script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
    script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'

  body

    - if user_signed_in?
      .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
        header.mdl-layout__header
          .mdl-layout__header-row
            span.mdl-layout-title
              = link_to issue_reports_path do 
                = image_tag("logo.svg", :class => "logo")
            .mdl-layout-spacer
            nav.mdl-navigation
              = link_to issue_reports_path, :class => "mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white" do
                span.ca-issue  
                span.mdl-layout--large-screen-only
                  '  Problemas reportados  
              - if current_user.admin != nil
                = link_to issues_path, :class => "mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white" do
                  span.ca-category  
                  span.mdl-layout--large-screen-only
                    '  Categorias
                  
              = link_to(destroy_user_session_path, :method => :delete, :class => "mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white") do
                span.ca-logout
                span.mdl-layout--large-screen-only
                  '  Logout

        main.mdl-layout__content
          .page-content
            = yield

    - else
      - if !notice.nil?
        .notice
          = notice
      - elsif !alert.nil?
        .alert
          = alert

      = yield